# Generated by Django 4.1.2 on 2022-10-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_booked_by_alter_bookinguser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_in',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_out',
            field=models.DateField(),
        ),
    ]
